CREATE TABLE bed_occupations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bed_id       BIGINT NOT NULL REFERENCES beds(id) ON DELETE CASCADE,
    patient_id   BIGINT NOT NULL,
    admission_id BIGINT NOT NULL,
    started_at   TIMESTAMP NOT NULL,
    ended_at     TIMESTAMP
);

CREATE UNIQUE INDEX uq_bed_open_occupation ON bed_occupations (bed_id) WHERE ended_at IS NULL;
CREATE INDEX idx_bed_occupations_admission ON bed_occupations (admission_id);
CREATE INDEX idx_bed_occupations_patient ON bed_occupations (patient_id);
CREATE INDEX idx_bed_occupations_started ON bed_occupations (started_at DESC);
