spring.application.name=identity-service
spring.profiles.active=dev
server.port=8081

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.access-expiration-seconds=3600
app.jwt.refresh-expiration-seconds=2592000

app.bootstrap.auto-provision=true
app.bootstrap.username=admin
app.bootstrap.password=Admin@Afya2026!
app.bootstrap.full-name=Administrateur Afya

management.endpoints.web.exposure.include=health,info

app.services.audit-base-url=${AUDIT_SERVICE_BASE_URL:http://localhost:8087}
app.audit.enabled=${AUDIT_ENABLED:true}
app.audit.ingestion-key=${AUDIT_INGESTION_KEY:dev-audit-ingestion-key}
logging.pattern.level=%5p [corr:%X{correlationId:-na}]
