CREATE TABLE medical_antecedents (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id   BIGINT       NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
    type         VARCHAR(20)  NOT NULL,
    description  VARCHAR(2000) NOT NULL,
    event_date   DATE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_medical_antecedents_patient ON medical_antecedents (patient_id);

CREATE TABLE emergency_contacts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id    BIGINT       NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
    first_name    VARCHAR(80)  NOT NULL,
    last_name     VARCHAR(80)  NOT NULL,
    relationship  VARCHAR(80)  NOT NULL,
    phone         VARCHAR(120) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_emergency_contacts_patient ON emergency_contacts (patient_id);
