@startuml MD01_AuthService
title Modèle du domaine — Auth Service (MD-01)

skinparam classBackgroundColor #D5F5E3
skinparam classBorderColor #1E8449
skinparam classArrowColor #1E8449
skinparam classFontStyle bold

class Credential {
  - id : Integer
  - utilisateurId : Integer
  - identifiant : String
  - motDePasseHash : String
  - statut : {ACTIF, INACTIF, BLOQUE}
  - tentativesEchouees : Integer
  - dernierAcces : DateTime
}

class TokenJWT {
  - id : Integer
  - credentialId : Integer
  - token : String
  - role : String
  - serviceId : Integer
  - dateEmission : DateTime
  - dateExpiration : DateTime
  - statut : {VALIDE, EXPIRE, REVOQUE}
}

class JournalConnexion {
  - id : Integer
  - credentialId : Integer
  - dateHeure : DateTime
  - adresseIP : String
  - action : {CONNEXION, DECONNEXION, ECHEC}
}

Credential "1" -- "0..*" TokenJWT : génère >
Credential "1" -- "0..*" JournalConnexion : produit >

@enduml
