@startuml MD04_PatientService
title Modèle du domaine — Patient Service (MD-04)

skinparam classBackgroundColor #F9EBEA
skinparam classBorderColor #922B21
skinparam classArrowColor #922B21
skinparam classFontStyle bold

class Patient {
  - id : Integer
  - numDossier : String
  - nom : String
  - prenom : String
  - dateNaissance : Date
  - sexe : {M, F}
  - groupeSanguin : String
  - adresse : String
  - commune : String
  - contact : String
  - contactUrgence : String
  - dateEnregistrement : DateTime
}

class AntecedentMedical {
  - id : Integer
  - patientId : Integer
  - type : {MEDICAL, CHIRURGICAL, FAMILIAL, ALLERGIE}
  - description : String
  - date : Date
}

class ContactUrgence {
  - id : Integer
  - patientId : Integer
  - nom : String
  - prenom : String
  - lienParente : String
  - telephone : String
}

Patient "1" *-- "0..*" AntecedentMedical : possède >
Patient "1" *-- "0..*" ContactUrgence : a >

@enduml
