@startuml MD05_AdmissionService
title Modèle du domaine — Admission Service (MD-05)

skinparam classBackgroundColor #EAF2F8
skinparam classBorderColor #1A5276
skinparam classArrowColor #1A5276
skinparam classFontStyle bold

class Admission {
  - id : Integer
  - numAdmission : String
  - patientId : Integer
  - receptionnisteId : Integer
  - type : {NORMALE, URGENCE}
  - motif : String
  - dateEntree : DateTime
  - statut : {EN_COURS, CLOTURE}
}

class Affectation {
  - id : Integer
  - admissionId : Integer
  - serviceId : Integer
  - litNum : String
  - dateAffectation : DateTime
}

class Transfert {
  - id : Integer
  - admissionId : Integer
  - serviceSourceId : Integer
  - serviceDestinationId : Integer
  - date : DateTime
  - motif : String
  - enregistrePar : Integer
}

class Sortie {
  - id : Integer
  - admissionId : Integer
  - dateSortie : DateTime
  - typeSortie : {GUERI, TRANSFERE_EXTERNE, DECEDE, CONTRE_AVIS_MEDICAL}
  - instructionsPost : String
  - enregistrePar : Integer
}

class NotificationAdmission {
  - id : Integer
  - admissionId : Integer
  - destinataireId : Integer
  - type : {HOSPITALISATION, SORTIE_AUTORISEE, TRANSFERT}
  - dateEnvoi : DateTime
  - statut : {ENVOYEE, LUE}
}

Admission "1" *-- "1" Affectation : génère >
Admission "1" -- "0..*" Transfert : fait l'objet de >
Admission "1" -- "0..1" Sortie : se termine par >
Admission "1" -- "0..*" NotificationAdmission : produit >

@enduml
