@startuml MD06_MedicalService
title Modèle du domaine — Medical Service (MD-06)

skinparam classBackgroundColor #FDEDEC
skinparam classBorderColor #A93226
skinparam classArrowColor #A93226
skinparam classFontStyle bold

class DossierMedical {
  - id : Integer
  - patientId : Integer
  - dateCreation : Date
  - medecinReferentId : Integer
}

class Consultation {
  - id : Integer
  - dossierMedicalId : Integer
  - medecinId : Integer
  - admissionId : Integer
  - date : DateTime
  - motif : String
  - observations : String
  - diagnosticPrincipal : String
  - diagnosticsAssocies : String
}

class Prescription {
  - id : Integer
  - consultationId : Integer
  - patientId : Integer
  - medecinId : Integer
  - date : Date
  - statut : {ACTIVE, EXECUTEE, ANNULEE}
}

class Medicament {
  - id : Integer
  - prescriptionId : Integer
  - nom : String
  - posologie : String
  - voieAdministration : {ORALE, INJECTABLE, TOPIQUE, INHALE}
  - duree : String
  - frequence : String
}

class DecisionMedicale {
  - id : Integer
  - consultationId : Integer
  - patientId : Integer
  - medecinId : Integer
  - type : {HOSPITALISATION, SORTIE}
  - date : DateTime
  - serviceDestId : Integer
  - instructions : String
}

DossierMedical "1" *-- "0..*" Consultation : contient >
Consultation "1" *-- "0..*" Prescription : génère >
Prescription "1" *-- "1..*" Medicament : comprend >
Consultation "1" -- "0..1" DecisionMedicale : conduit à >

@enduml
