@startuml MD07_LabService
title Modèle du domaine — Lab Service (MD-07)

skinparam classBackgroundColor #FEF9E7
skinparam classBorderColor #9A7D0A
skinparam classArrowColor #9A7D0A
skinparam classFontStyle bold

class TypeExamen {
  - id : Integer
  - nom : String
  - description : String
  - categorie : {BIOLOGIE, IMAGERIE, BACTERIOLOGIE, AUTRE}
  - parametres : String
}

class DemandeExamen {
  - id : Integer
  - patientId : Integer
  - medecinId : Integer
  - admissionId : Integer
  - dateDemande : DateTime
  - urgence : {NORMAL, URGENT}
  - statut : {EN_ATTENTE, PRELEVEMENT_EFFECTUE, RESULTATS_DISPONIBLES, REPORTE}
  - commentaire : String
}

class LigneDemandeExamen {
  - id : Integer
  - demandeId : Integer
  - typeExamenId : Integer
}

class Prelevement {
  - id : Integer
  - demandeId : Integer
  - laboratinId : Integer
  - dateHeure : DateTime
  - typeEchantillon : String
}

class ResultatExamen {
  - id : Integer
  - demandeId : Integer
  - patientId : Integer
  - laboratinId : Integer
  - dateResultat : DateTime
  - annotation : String
}

class ParametreResultat {
  - id : Integer
  - resultatId : Integer
  - parametre : String
  - valeur : String
  - unite : String
  - valeurReferenceMin : String
  - valeurReferenceMax : String
  - estAnormal : Boolean
}

TypeExamen "1" -- "0..*" LigneDemandeExamen : référencé dans >
DemandeExamen "1" *-- "1..*" LigneDemandeExamen : contient >
DemandeExamen "1" -- "0..1" Prelevement : fait l'objet de >
DemandeExamen "1" -- "0..1" ResultatExamen : produit >
ResultatExamen "1" *-- "1..*" ParametreResultat : détaillé par >

@enduml
