CREATE TABLE credentials (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL UNIQUE,
    username        VARCHAR(80) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIF',
    failed_attempts INT NOT NULL DEFAULT 0,
    last_access_at  TIMESTAMP,
    locked_at       TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_credentials_status CHECK (status IN ('ACTIF', 'INACTIF', 'BLOQUE'))
);
