-- MD-01 — TokenJWT : traçabilité des tokens JWT émis
CREATE TABLE issued_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti         VARCHAR(64)  NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL,
    username    VARCHAR(80)  NOT NULL,
    token_type  VARCHAR(10)  NOT NULL DEFAULT 'ACCESS',
    issued_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked_at  TIMESTAMPTZ,
    CONSTRAINT chk_token_type CHECK (token_type IN ('ACCESS', 'REFRESH'))
);

CREATE INDEX idx_issued_tokens_user_id     ON issued_tokens (user_id);
CREATE INDEX idx_issued_tokens_expires_at  ON issued_tokens (expires_at);

-- MD-01 — JournalConnexion : historique des connexions réussies et échouées
CREATE TABLE login_journal (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(80)  NOT NULL,
    user_id     BIGINT,
    outcome     VARCHAR(40)  NOT NULL,
    ip_address  VARCHAR(45),
    occurred_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_login_outcome CHECK (outcome IN (
        'SUCCESS',
        'FAILURE_BAD_PASSWORD',
        'FAILURE_USER_NOT_FOUND',
        'FAILURE_ACCOUNT_LOCKED',
        'FAILURE_ACCOUNT_INACTIVE'
    ))
);

CREATE INDEX idx_login_journal_username    ON login_journal (username);
CREATE INDEX idx_login_journal_occurred_at ON login_journal (occurred_at DESC);
CREATE INDEX idx_login_journal_outcome     ON login_journal (outcome);
