CREATE TABLE vital_sign_readings (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id           BIGINT       NOT NULL,
    admission_id         BIGINT       NOT NULL,
    nurse_username       VARCHAR(80)  NOT NULL,
    recorded_at          TIMESTAMP    NOT NULL,
    slot                 VARCHAR(20),
    systolic_bp          INT,
    diastolic_bp         INT,
    pulse_bpm            INT,
    respiratory_rate     INT,
    temperature_celsius  DECIMAL(5, 2),
    weight_kg            DECIMAL(6, 2),
    spo2                 DECIMAL(5, 2),
    diuresis_ml          INT,
    stools_note          VARCHAR(500),
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_vital_sign_admission ON vital_sign_readings (admission_id, recorded_at DESC);
CREATE INDEX idx_vital_sign_patient ON vital_sign_readings (patient_id, recorded_at DESC);

CREATE TABLE vital_sign_alerts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vital_sign_reading_id BIGINT     NOT NULL REFERENCES vital_sign_readings (id) ON DELETE CASCADE,
    parameter           VARCHAR(40)  NOT NULL,
    measured_value      VARCHAR(40)  NOT NULL,
    threshold_label     VARCHAR(80)  NOT NULL,
    alert_level         VARCHAR(20)  NOT NULL,
    alert_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_vital_sign_alerts_reading ON vital_sign_alerts (vital_sign_reading_id);
