CREATE TABLE prescription_notifications (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_line_id         BIGINT       NOT NULL UNIQUE,
    patient_id                   BIGINT       NOT NULL,
    drug_name                    VARCHAR(200) NOT NULL,
    nurse_username               VARCHAR(80),
    medication_administration_id BIGINT,
    sent_at                      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status                       VARCHAR(20)  NOT NULL DEFAULT 'ENVOYEE',
    read_at                      TIMESTAMP,
    executed_at                  TIMESTAMP
);

CREATE INDEX idx_prescription_notifications_patient ON prescription_notifications (patient_id);
CREATE INDEX idx_prescription_notifications_status ON prescription_notifications (status);
