CREATE TABLE exam_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120) NOT NULL UNIQUE,
    description  VARCHAR(500),
    category     VARCHAR(32) NOT NULL,
    parameters   VARCHAR(1000),
    active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exam_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id    BIGINT NOT NULL,
    doctor_id     BIGINT NOT NULL,
    admission_id  BIGINT,
    requested_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    urgency       VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    status        VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    comment       VARCHAR(1000),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exam_request_lines (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     BIGINT NOT NULL REFERENCES exam_requests(id) ON DELETE CASCADE,
    exam_type_id   BIGINT NOT NULL REFERENCES exam_types(id),
    UNIQUE (request_id, exam_type_id)
);

CREATE TABLE specimen_collections (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id       BIGINT NOT NULL UNIQUE REFERENCES exam_requests(id) ON DELETE CASCADE,
    lab_technician_id BIGINT NOT NULL,
    collected_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sample_type      VARCHAR(120) NOT NULL
);

CREATE TABLE exam_results (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id       BIGINT NOT NULL UNIQUE REFERENCES exam_requests(id) ON DELETE CASCADE,
    patient_id       BIGINT NOT NULL,
    lab_technician_id BIGINT NOT NULL,
    resulted_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    annotation       VARCHAR(2000)
);

CREATE TABLE result_parameters (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id           BIGINT NOT NULL REFERENCES exam_results(id) ON DELETE CASCADE,
    parameter_name      VARCHAR(120) NOT NULL,
    value               VARCHAR(120) NOT NULL,
    unit                VARCHAR(40),
    reference_min       VARCHAR(40),
    reference_max       VARCHAR(40),
    abnormal            BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_exam_requests_patient ON exam_requests(patient_id);
CREATE INDEX idx_exam_requests_status ON exam_requests(status);
CREATE INDEX idx_exam_request_lines_request ON exam_request_lines(request_id);
