CREATE TABLE vital_sign_readings (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id         BIGINT NOT NULL REFERENCES admissions(id) ON DELETE CASCADE,
    recorded_at          TIMESTAMP NOT NULL,
    slot                 VARCHAR(20),
    systolic_bp          INT,
    diastolic_bp         INT,
    pulse_bpm            INT,
    temperature_celsius  DECIMAL(5, 2),
    weight_kg            DECIMAL(6, 2),
    diuresis_ml          INT,
    stools_note          VARCHAR(500)
);

CREATE INDEX idx_vital_sign_admission ON vital_sign_readings(admission_id, recorded_at DESC);
