CREATE TABLE emergency_visit_timeline_events (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emergency_visit_id   BIGINT NOT NULL REFERENCES emergency_visits(id),
    event_type           VARCHAR(40) NOT NULL,
    details              VARCHAR(500),
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_emergency_timeline_visit_created ON emergency_visit_timeline_events(emergency_visit_id, created_at);
