CREATE TABLE discharges (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id                BIGINT       NOT NULL UNIQUE REFERENCES admissions (id),
    discharged_at               TIMESTAMP    NOT NULL,
    discharge_type              VARCHAR(30)  NOT NULL,
    post_discharge_instructions VARCHAR(2000),
    recorded_by_username        VARCHAR(80)  NOT NULL,
    created_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admission_notifications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id        BIGINT       NOT NULL REFERENCES admissions (id),
    recipient_user_id   BIGINT,
    notification_type   VARCHAR(30)  NOT NULL,
    sent_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status              VARCHAR(20)  NOT NULL DEFAULT 'ENVOYEE',
    read_at             TIMESTAMP
);

CREATE INDEX idx_admission_notifications_admission ON admission_notifications (admission_id);
CREATE INDEX idx_admission_notifications_recipient ON admission_notifications (recipient_user_id);
