CREATE TABLE consultations (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id              BIGINT NOT NULL,
    admission_id            BIGINT NOT NULL,
    doctor_name             VARCHAR(80) NOT NULL,
    reason                  VARCHAR(255),
    consultation_date_time  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE consultation_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consultation_id  BIGINT NOT NULL REFERENCES consultations(id) ON DELETE CASCADE,
    patient_id       BIGINT NOT NULL,
    event_type       VARCHAR(40) NOT NULL,
    content          VARCHAR(4000) NOT NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_consultations_patient ON consultations(patient_id);
CREATE INDEX idx_consultations_admission ON consultations(admission_id);
CREATE INDEX idx_consultations_date ON consultations(consultation_date_time);
CREATE INDEX idx_consultation_events_patient ON consultation_events(patient_id, created_at);
CREATE INDEX idx_consultation_events_consultation ON consultation_events(consultation_id);
