@startuml ACTIVITE_COLONNE_RECEPTIONNISTE_AFYA
title "Activité — colonne Réceptionniste"

|Réceptionniste|
start
:S'authentifier;

|identity-service|
:Valider identifiants;

|Réceptionniste|
if (Besoin patient ?) then (Recherche)
  :Saisir critère de recherche;
  |patient-service|
  :Rechercher le patient;
  |Réceptionniste|
  if (Trouvé ?) then (oui)
    :Afficher la fiche;
  else (non)
    :Créer un patient;
    |patient-service|
    :Enregistrer et journaliser;
    |Réceptionniste|
    :Afficher n° dossier;
  endif
else (Admission directe)
  :Patient déjà connu;
endif

:Choisir service et date;

|care-entry-service|
:Créer admission;

|catalog-service|
:Vérifier capacité;

if (Disponible ?) then (oui)
  |stay-service|
  :Ouvrir séjour;
  :Journaliser;
  |Réceptionniste|
  :Confirmer admission;
  stop
else (non)
  |Réceptionniste|
  :Afficher erreur;
  :Corriger le choix;
  stop
endif
@enduml
