@startuml ACTIVITE_COLONNE_INFIRMIER_AFYA
title "Activité — colonne Infirmier"

|Infirmier|
start
:S'authentifier;

|identity-service|
:Valider identifiants;

|Infirmier|
:Rechercher patient;

|clinical-record-service|
:Charger dossier et soins;

|Infirmier|
if (Nouveau soin ?) then (oui)
  :Saisir soin;
  |clinical-record-service|
  :Enregistrer soin infirmier;
  |Infirmier|
  :Fin;
endif

if (Administration ?) then (oui)
  :Choisir prescription et dose;
  |clinical-record-service|
  :Enregistrer administration;
  |Infirmier|
  :Fin;
endif

:Fin;
stop
@enduml
