@startuml ACTIVITE_CAPACITES_INFIRMIER_AFYA
title "Diagramme d'activité côté Infirmier(ère) (SI Afya)"
' Détail : ACTIVITE_SOIN_INFIRMIER_AFYA.

start
label authentification
:S'authentifier;
if (Authentification ?) then (Si échec)
  ->authentification;
else (Si réussie)
  :Choisir opération;
  fork
    :Logout;
    ->authentification;
  fork again
    :Rechercher un patient;
    if (Patient trouvé ?) then (oui)
      :Afficher la fiche patient;
    else (non)
      :Afficher message patient non trouvé;
    endif
    :Choisir opération;
  fork again
    :Consulter le dossier médical du patient;
    :Choisir opération;
  fork again
    :Consulter les prescriptions;
    :Choisir opération;
  fork again
    :Enregistrer les soins infirmiers;
    :Choisir opération;
  fork again
    :Marquer l'exécution d'une prescription;
    if (Prescription valide ?) then (oui)
      :Enregistrer l'administration;
      :Afficher confirmation;
    else (non)
      :Afficher erreur métier;
    endif
    :Choisir opération;
  fork again
    :Consulter l'historique des interventions;
    :Choisir opération;
  end fork
endif
stop
@enduml
