@startuml ACTIVITE_ENREGISTRER_PATIENT_AFYA
title "Diagramme d'activité — Enregistrer / rechercher un patient (réceptionniste)"
|Réceptionniste|
start
if (Objectif ?) then (Rechercher)
  :Saisir nom ou n° dossier;
  |Front / BFF|
  :GET /api/v1/patients?search=…;
  |patient-service|
  :Requête sur patients;
  if (Résultat trouvé ?) then (oui)
    |Réceptionniste|
    :Afficher fiche patient;
  else (non)
    :Message patient non trouvé;
  endif
else (Enregistrer)
  :Saisir identité, contacts, date naissance…;
  |Front / BFF|
  :POST /api/v1/patients;
  |patient-service|
  if (Données valides ?) then (oui)
    :Générer dossierNumber unique;
    :Persister Patient;
    :Audit PATIENT_CREATED;
    |Réceptionniste|
    :Afficher succès + n° dossier;
  else (non)
    :Erreur validation;
  endif
endif
stop
@enduml
