@startuml ACTIVITE_GENERALE_AFYA
title "Diagramme d'activité — Vue générale (SI Afya)"

|Utilisateur|
start
:S'authentifier;

|identity-service|
:Valider identifiants et rôles;

|Utilisateur|
if (Cas d'utilisation ?) then (Utilisateurs)
  |identity-service|
  :Administrer comptes et rôles;
elseif (Services) then
  |catalog-service|
  :Administrer catalogue et lits;
elseif (Patient) then
  |patient-service|
  :Rechercher ou enregistrer;
elseif (Admission) then
  |care-entry-service|
  :Créer admission;
  |stay-service|
  :Ouvrir séjour;
elseif (Prise en charge) then
  |clinical-record-service|
  :Diagnostic et prescription;
  |care-entry-service|
  :Sortie ou transfert;
elseif (Soins) then
  |clinical-record-service|
  :Soins et administration;
else (Lecture)
  :Consultation seule;
endif

stop

@enduml
