@startuml ACTIVITE_COLONNE_MEDECIN_AFYA
title "Activité — colonne Médecin"

|Médecin|
start
:S'authentifier;

|identity-service|
:Valider identifiants;

|Médecin|
:Ouvrir dossier et consultation;

|clinical-record-service|
:Charger dossier et chronologie;

|Médecin|
if (Diagnostic ?) then (oui)
  :Saisir maladie et observations;
  |clinical-record-service|
  :Enregistrer diagnostic;
  |Médecin|
  :Fin;
endif

if (Prescription ?) then (oui)
  :Saisir traitement;
  |clinical-record-service|
  :Enregistrer prescription;
  |Médecin|
  :Fin;
endif

:Décider sortie ou transfert;

if (Sortie ?) then (oui)
  |care-entry-service|
  :Clôturer admission;
  |stay-service|
  :Clôturer séjour;
else (Transfert)
  |care-entry-service|
  :Créer transfert;
  |stay-service|
  :Mettre à jour séjour;
endif

|audit-service|
:Journaliser décision;

|Médecin|
:Fin;
stop
@enduml
