@startuml RELATIONS_GATEWAYS_BFF
title "Relations UML — Gateway/BFF Afya (controllers -> clients HTTP)"
skinparam classAttributeIconSize 0
hide empty members
hide circle

package "Controllers REST (BFF)" {
  class AuthBffController
  class UserBffController
  class PatientBffController
  class AdmissionBffController
  class EmergencyBffController
  class StayBffController
  class PatientClinicalBffController
  class ConsultationBffController
  class PrescriptionBffController
  class DiseaseCatalogBffController
  class HospitalServiceBffController
  class AuditBffController
  class StatsBffController
}

package "Clients HTTP" {
  class IdentityClient
  class PatientClient
  class CareEntryClient
  class StayClient
  class ClinicalRecordClient
  class CatalogClient
  class AuditClient
}

AuthBffController --> IdentityClient
UserBffController --> IdentityClient
PatientBffController --> PatientClient
AdmissionBffController --> CareEntryClient
EmergencyBffController --> CareEntryClient
StayBffController --> StayClient
PatientClinicalBffController --> ClinicalRecordClient
ConsultationBffController --> ClinicalRecordClient
PrescriptionBffController --> ClinicalRecordClient
DiseaseCatalogBffController --> ClinicalRecordClient
HospitalServiceBffController --> CatalogClient
AuditBffController --> AuditClient
StatsBffController --> AuditClient
StatsBffController --> CareEntryClient
StatsBffController --> ClinicalRecordClient

legend right
  Relation utilisée :
  --> association / appel
  (controller BFF vers client HTTP)
endlegend

@enduml
