@startuml RELATIONS_PERSISTANCE_AFYA
title "Vue relations uniquement — persistance Afya (analyse, français)"
skinparam linetype ortho
hide empty members
hide circle

legend right
  *-- composition
  -- association (FK)
  ..> dépendance (ref logique)
  Détail : TOUTES_LES_RELATIONS_UML_AFYA.md
endlegend

together {
  class UtilisateurCompte
  class Role
  class UtilisateurRole
  class SessionUtilisateur
  UtilisateurCompte "1" -- "0..*" UtilisateurRole
  Role "1" -- "0..*" UtilisateurRole
  UtilisateurCompte "1" -- "0..*" SessionUtilisateur
}

together {
  class Departement
  class ServiceHospitalier
  class Lit
  Departement "1" *-- "0..*" ServiceHospitalier
  ServiceHospitalier "1" *-- "0..*" Lit
}

together {
  class Patient
  class Admission
  class DemandeTransfert
  class VisiteUrgence
  class Sejour
  class FormulaireHospitalisation
  class DossierMedical
  class Consultation
  class EvenementConsultation
  class Diagnostic
  class NoteClinique
  class Prescription
  class SoinInfirmier
  class AdministrationMedicament
  class DocumentClinique
  class CatalogueMaladie
  class JournalActivite

  Admission "1" -- "0..*" DemandeTransfert
  Sejour "1" *-- "0..1" FormulaireHospitalisation
  DossierMedical "1" *-- "0..*" Diagnostic
  DossierMedical "1" *-- "0..*" NoteClinique
  DossierMedical "1" *-- "0..*" Prescription
  DossierMedical "1" *-- "0..*" SoinInfirmier
  DossierMedical "1" *-- "0..*" DocumentClinique
  Consultation "1" *-- "0..*" EvenementConsultation
  Prescription "1" -- "0..*" AdministrationMedicament

  Patient ..> Admission : identifiantPatient
  Patient ..> VisiteUrgence : identifiantPatient
  Patient ..> DossierMedical : identifiantPatient
  Patient ..> Consultation : identifiantPatient
  Patient ..> Sejour : identifiantPatient
  ServiceHospitalier ..> Admission : identifiantService
  Admission ..> Sejour : identifiantAdmission
  Admission ..> Consultation : identifiantAdmission
}

@enduml
