-- MD-02 — Affectation datée utilisateur → service hospitalier
-- Remplace le simple Set<Long> hospitalServiceIds par une entité avec dates début/fin

CREATE TABLE user_assignments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    hospital_service_id BIGINT      NOT NULL,
    start_date          DATE        NOT NULL,
    end_date            DATE,
    CONSTRAINT chk_assignment_dates CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE INDEX idx_user_assignments_user_id          ON user_assignments (user_id);
CREATE INDEX idx_user_assignments_service_id        ON user_assignments (hospital_service_id);
CREATE INDEX idx_user_assignments_end_date          ON user_assignments (end_date);

-- Migrer les affectations existantes depuis user_hospital_services vers user_assignments
-- (start_date = date du jour, end_date = NULL = affectation toujours active)
INSERT INTO user_assignments (user_id, hospital_service_id, start_date)
SELECT user_id, hospital_service_id, CURRENT_DATE
FROM   user_hospital_services
ON CONFLICT DO NOTHING;
