app.services.auth-base-url=${AUTH_SERVICE_URL:http://auth:8081}
app.services.user-base-url=${USER_SERVICE_URL:http://user:8089}
app.services.hospital-base-url=${HOSPITAL_SERVICE_URL:http://hospital:8082}
app.services.patient-base-url=${PATIENT_SERVICE_URL:http://patient:8083}
app.services.admission-base-url=${ADMISSION_SERVICE_URL:http://admission:8084}
app.services.medical-base-url=${MEDICAL_SERVICE_URL:http://medical:8085}
app.services.nursing-base-url=${NURSING_SERVICE_URL:http://nursing:8093}
app.services.lab-base-url=${LAB_SERVICE_URL:http://lab:8092}
app.services.audit-base-url=${AUDIT_SERVICE_URL:http://audit:8087}
app.services.report-base-url=${REPORT_SERVICE_URL:http://report:8094}

app.jwt.access-secret=${JWT_ACCESS_SECRET}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
