@startuml CONCEPTION_SEQUENCE_ADMISSION_AFYA
title "Diagramme de séquence de conception — Enregistrer une admission"
autonumber

actor "Réceptionniste" as User
participant "SPA Web" as Web
participant "BFF" as BFF
participant "AdmissionController" as Ctrl
participant "AdmissionService" as Svc
participant "PatientServiceClient" as PatClient
participant "patient-service" as PatSvc
participant "CatalogServiceClient" as CatClient
participant "catalog-service" as CatSvc
participant "AdmissionWriter" as Writer
participant "AdmissionRepository" as Repo
participant "StayServiceClient" as StayClient
participant "stay-service" as StaySvc
participant "RestAuditEventPublisher" as Audit
participant "audit-service" as AuditSvc

User -> Web : formulaire admission
Web -> BFF : POST /api/v1/admissions + JWT
BFF -> Ctrl : POST /api/v1/admissions
Ctrl -> Svc : admit(request, bearerToken)

Svc -> PatClient : getPatient(patientId, auth)
PatClient -> PatSvc : GET /api/v1/patients/{id}
PatSvc --> PatClient : 200 PatientSummary
PatClient --> Svc : patient valide

Svc -> CatClient : getHospitalService(serviceId, auth)
CatClient -> CatSvc : GET /api/v1/hospital-services/{id}
CatSvc --> CatClient : 200 HospitalServiceSummary
CatClient --> Svc : service actif

Svc -> Writer : persist(Admission)
Writer -> Repo : save(Admission)
Repo --> Writer : Admission
Writer --> Svc : admission persistée

Svc -> StayClient : openStay(StayOpenRequest, auth)
StayClient -> StaySvc : POST /api/v1/stays
StaySvc --> StayClient : 201 StaySummary
StayClient --> Svc : séjour ouvert

Svc -> Audit : publish(ADMISSION_CREATED)
Audit -> AuditSvc : POST /api/v1/audit/events
AuditSvc --> Audit : 201 Created
Audit --> Svc : ok

Svc --> Ctrl : AdmissionResponse
Ctrl --> BFF : 201 Created
BFF --> Web : JSON
Web --> User : confirmation écran

@enduml
