{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "afya.secretName" . }}
  namespace: {{ include "afya.namespace" . }}
  labels:
    {{- include "afya.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-access-secret: {{ required "secrets.jwtAccessSecret requis" .Values.secrets.jwtAccessSecret | quote }}
  jwt-refresh-secret: {{ required "secrets.jwtRefreshSecret requis" .Values.secrets.jwtRefreshSecret | quote }}
  audit-ingestion-key: {{ required "secrets.auditIngestionKey requis" .Values.secrets.auditIngestionKey | quote }}
  minio-access-key: {{ .Values.secrets.minioAccessKey | quote }}
  minio-secret-key: {{ .Values.secrets.minioSecretKey | quote }}
  {{- range $key, $db := .Values.databases }}
  {{ $key }}-db-password: {{ required (printf "databases.%s.password requis" $key) $db.password | quote }}
  {{- end }}
{{- end }}
